apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: upcj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: upcj
    app.kubernetes.io/part-of: byoc-app-ykqc
  name: upcj
spec:
  rules:
  - host: upcj-byoc-vdwo-tenant.apps.bb01aa5fd6f0af6bcc62.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: upcj
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
