apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: upcj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: upcj
    app.kubernetes.io/part-of: byoc-app-ykqc
  name: upcj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: upcj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: upcj
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-vdwo-tenant/byoc-app-ykqc/upcj@sha256:792264a6e116bbc4c4b8d1b01ddf5132a0a6f9a7cd998f81a3d65ce5ef8168d6
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
